redis:
  default:
    maxActive: 50 #最大的激活连接数,支持最高并发数
    maxIdle: 5  #最大的空闲连接数
    idleTimeout: 180 #最大的空闲连接等待时间，超过此时间后，空闲连接将被关闭
    servers:
      - address: 159.75.208.79:6379
        passwd: duoxiang88
  uc:
    maxActive: 50 #最大的激活连接数,支持最高并发数
    maxIdle: 5  #最大的空闲连接数
    idleTimeout: 180 #最大的空闲连接等待时间，超过此时间后，空闲连接将被关闭
    servers:
      - address: 159.75.208.79:6379
        passwd: duoxiang88