tencent:
  SmsSdkAppId: 1400555466
  SecretId: AKIDAC1e3D9qIWVFl25tSmqgKkvrZ3JKPHvK
  SecretKey: CNK2UgeRyHK9j4HFyTjlX3KM7dtCH8l9
  MobileCode: "+86"
  ReqMethod: POST
  Endpoint: sms.tencentcloudapi.com
  Region: ap-guangzhou
  SignMethod: TC3-HMAC-SHA256
  SignName: 多想云内容引擎
aliyun: